YUZU_COMPILE_FLAGS="-march=znver2 -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3"
YUZU_COMPILE_FLAGS+=" -msse4.1 -msse4.2 -mavx -mavx2 -msse4a -mno-fma4"
YUZU_COMPILE_FLAGS+=" -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul"
YUZU_COMPILE_FLAGS+=" -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd"
YUZU_COMPILE_FLAGS+=" -mno-avx512er -mno-avx512pf -mno-avx512vbmi"
YUZU_COMPILE_FLAGS+=" -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps"
YUZU_COMPILE_FLAGS+=" -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni"
YUZU_COMPILE_FLAGS+=" -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg"
YUZU_COMPILE_FLAGS+=" -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx"
YUZU_COMPILE_FLAGS+=" -mabm -mno-cldemote -mclflushopt -mclwb -mclzero -mcx16"
YUZU_COMPILE_FLAGS+=" -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf"
YUZU_COMPILE_FLAGS+=" -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri"
YUZU_COMPILE_FLAGS+=" -mmwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mprfchw"
YUZU_COMPILE_FLAGS+=" -mno-ptwrite -mrdpid -mrdrnd -mrdseed -mno-rtm"
YUZU_COMPILE_FLAGS+=" -mno-serialize -mno-sgx -msha -mno-shstk -mno-tbm"
YUZU_COMPILE_FLAGS+=" -mno-tsxldtrk -mno-vaes -mno-waitpkg -mwbnoinvd -mxsave"
YUZU_COMPILE_FLAGS+=" -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8"
YUZU_COMPILE_FLAGS+=" -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl"
YUZU_COMPILE_FLAGS+=" -mno-avxvnni -mno-avx512fp16 --param l1-cache-size=32"
YUZU_COMPILE_FLAGS+=" --param l1-cache-line-size=64 --param l2-cache-size=512"
YUZU_COMPILE_FLAGS+=" -mtune=znver2 -dumpbase -O3"
